In [2]:
print("hello world")

hello world


In [24]:
#https://qiita.com/sasayabaku/items/9e376ba8e38efe3bcf79
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.optimizers import Adam

from tensorflow.keras.layers import Dense, Activation, Dropout, Flatten
from tensorflow.keras.utils import plot_model, to_categorical
from keras.callbacks import TensorBoard

from keras.datasets import cifar10

In [1]:
import glob    #fileの名前の取得に必要
import numpy as np
import re
#https://qiita.com/neet-AI/items/2b3d7f743e4d6c6d8e10
from keras.preprocessing.image import load_img, img_to_array, array_to_img
from keras.preprocessing.image import random_rotation, random_shift, random_zoom
from keras.layers.convolutional import Conv2D
from keras.layers.pooling import MaxPooling2D
from keras.layers.core import Activation
from keras.layers.core import Dense
from keras.layers.core import Dropout
from keras.layers.core import Flatten
from keras.models import Sequential
from keras.models import model_from_json
from keras.callbacks import LearningRateScheduler
from keras.callbacks import ModelCheckpoint
from keras.optimizers import Adam
from keras.utils import np_utils

route_name_dic = {
        "taketomi_route" : ["isigaki_dep","taketomi_dep"],
        "kurosima_route" : ["isigaki_dep","kurosima_dep"],
        "kohama_route" : ["isigaki_dep","kohama_dep"],
        "iriomote_uehara_route" : ["isigaki_dep","uehara_dep"],
        "hatoma_route" : ["isigaki_dep","hatoma_dep"],
        "iriomote_ohara_route" : ["isigaki_dep","ohara_dep"],
        "hateruma_route" : ["isigaki_dep","hateruma_dep"]
    } 
for key,value in route_name_dic.items():    #航路分回る(7回)
    #print(key,value)
    for i in value:    #出発港分回る
        print(i)
        dir = "../data/route/" + key + "/" + i + "/*.csv"
        print(dir)
        files = [p for p in glob.glob(dir, recursive=True)    #fileのpathを取得する
           if re.search(r'020-\d[891]-\d*.csv', p)]           #正規表現で2020-08~11分のcsvを抽出
        files.sort()
        print(files)
        
        #df = pd.read_csv('data/src/sample.csv')
    break

#files = glob.glob(dirname + "/*.jpeg")
#data/route/hateruma_route/hateruma_dep

isigaki_dep
../data/route/taketomi_route/isigaki_dep/*.csv
['../data/route/taketomi_route/isigaki_dep/2020-08-02.csv', '../data/route/taketomi_route/isigaki_dep/2020-08-03.csv', '../data/route/taketomi_route/isigaki_dep/2020-08-04.csv', '../data/route/taketomi_route/isigaki_dep/2020-08-05.csv', '../data/route/taketomi_route/isigaki_dep/2020-08-06.csv', '../data/route/taketomi_route/isigaki_dep/2020-08-07.csv', '../data/route/taketomi_route/isigaki_dep/2020-08-08.csv', '../data/route/taketomi_route/isigaki_dep/2020-08-09.csv', '../data/route/taketomi_route/isigaki_dep/2020-08-10.csv', '../data/route/taketomi_route/isigaki_dep/2020-08-11.csv', '../data/route/taketomi_route/isigaki_dep/2020-08-12.csv', '../data/route/taketomi_route/isigaki_dep/2020-08-13.csv', '../data/route/taketomi_route/isigaki_dep/2020-08-14.csv', '../data/route/taketomi_route/isigaki_dep/2020-08-15.csv', '../data/route/taketomi_route/isigaki_dep/2020-08-16.csv', '../data/route/taketomi_route/isigaki_dep/2020-08-17.cs

In [4]:
import re
def date_re(x):
    return re.sub('(\d*:\d*)(\W*)', '\\2', x)
x = "09:30上原経由"
print(date_re(x))

上原経由


In [21]:
import pandas as pd
from datetime import date
from datetime import time
from datetime import datetime
from datetime import datetime as dt

img_time_com = ["08:00:00","10:00:00","12:00:00","14:00:00","16:00:00"]
img_time = ["07:00:00","09:00:00","11:00:00","13:00:00","15:00:00","17:00:00"]
for i in range(0,len(files)):
    df = pd.read_csv(files[i],  names=('Time', 'Label', 'Date'))
    
    #df = df.reset_index(drop=True)
    #print(df)
    df['DateTime'] = df['Date'].str.cat(df['Time'], sep=' ')
    #df['Date'] = pd.to_datetime(df['Date'])
    df['DateTime'] = pd.to_datetime(df['DateTime'])
    
    img_path = df_loop(df)
    arrlist = img_lo(img_path)
    #df = df.drop('Time', axis=1)
    #df['Date'] = pd.to_datetime(df['Date'])
    #print(df)
#     dftime = df["Time"]
#     print(dftime)

    #print(df)
    #print(df['Date'].dtype)
    #convert_time = pd.to_datetime(df, format='%Y%m%d')

<class 'str'>
2020-08-02 07:50:00
<class 'datetime.datetime'>
2020-08-02 08:00:00
2020-08-02 07:50:00
0
../data/windy_img/2020-08-02/2020-08-02 07:00:00.png
True
<class 'str'>
2020-08-02 08:50:00
<class 'datetime.datetime'>
2020-08-02 08:00:00
2020-08-02 08:50:00
0
<class 'datetime.datetime'>
2020-08-02 10:00:00
2020-08-02 08:50:00
1
../data/windy_img/2020-08-02/2020-08-02 09:00:00.png
True
<class 'str'>
2020-08-02 09:50:00
<class 'datetime.datetime'>
2020-08-02 08:00:00
2020-08-02 09:50:00
0
<class 'datetime.datetime'>
2020-08-02 10:00:00
2020-08-02 09:50:00
1
../data/windy_img/2020-08-02/2020-08-02 09:00:00.png
True
<class 'str'>
2020-08-02 10:50:00
<class 'datetime.datetime'>
2020-08-02 08:00:00
2020-08-02 10:50:00
0
<class 'datetime.datetime'>
2020-08-02 10:00:00
2020-08-02 10:50:00
1
<class 'datetime.datetime'>
2020-08-02 12:00:00
2020-08-02 10:50:00
2
../data/windy_img/2020-08-02/2020-08-02 11:00:00.png
True
<class 'str'>
2020-08-02 11:50:00
<class 'datetime.datetime'>
2020-08-02

FileNotFoundError: [Errno 2] No such file or directory: '../data/windy_img/2020-08-03/2020-08-03 07:00:00.png'

In [9]:
from datetime import datetime as dt

def df_loop(df):
    img_path = []

    for row in df.itertuples():    #dfを一行ずつ回す
    #     print(type(row))
    #     print(row)
    #     print('------')

        print(type(row[3]))
        print(row.DateTime)


        #for文で回す
        for i in range(len(img_time_com)):    #画像の比較のために5回回す
           # print(len(img_time_com))
            comtime = row[3] + " " + img_time_com[i]
            #print(comtime)
            #tstr = comtime#'2012-12-29 13:49:37'
            comdatetime = dt.strptime(comtime, '%Y-%m-%d %H:%M:%S')
            print(type(comdatetime))
            print(comdatetime)
            print(row.DateTime)
            print(i)
            if row.DateTime < comdatetime:    #航路出発時間 < 画像の取得時間
                img_path.append("../data/windy_img/"+row[3]+"/"+row[3]+ " " +img_time[i]+".png")
                print("../data/windy_img/"+row[3]+"/"+row[3]+ " " +img_time[i]+".png")
                print("True")
                break
            elif 4 == i:
                img_path.append("../data/windy_img/"+row[3]+"/"+row[3]+ " " +img_time[5]+".png")
                print("../data/windy_img/"+row[3]+"/"+row[3]+ " " +img_time[5]+".png")
    return img_path

In [10]:
print(img_path)

['../data/windy_img/2020-11-15/2020-11-15 07:00:00.png']


In [17]:
def img_lo(img_path):
    arrlist = []    #imgのnumpy行列
    hw = {"height":16, "width":16}        # リストではなく辞書型 中かっこで囲む
    for imgfile in img_path:
        img = load_img(imgfile, target_size=(hw["height"], hw["width"]))    # 画像ファイルの読み込み
        array = img_to_array(img) / 255                                     # 画像ファイルのnumpy化
        arrlist.append(array)  
    return arrlist

In [22]:
print(arrlist)

[array([[[1.        , 1.        , 1.        ],
        [0.45882353, 0.45882353, 0.45882353],
        [1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ],
        [0.23921569, 0.40392157, 0.64705884],
        [0.23921569, 0.40392157, 0.65882355],
        [0.24313726, 0.40784314, 0.6784314 ],
        [0.1764706 , 0.29803923, 0.5058824 ],
        [0.78431374, 0.8117647 , 0.85882354],
        [0.24313726, 0.40784314, 0.72156864],
        [0.23921569, 0.38431373, 0.69411767],
        [0.23137255, 0.35686275, 0.6627451 ],
        [0.22745098, 0.3372549 , 0.64705884],
        [0.3764706 , 0.46666667, 0.77254903],
        [0.99607843, 0.9529412 , 0.8901961 ],
        [0.22352941, 0.29411766, 0.6       ]],

       [[0.23137255, 0.39607844, 0.5882353 ],
        [0.23529412, 0.39607844, 0.6039216 ],
        [0.23529412, 0.4       , 0.62352943],
        [0.23921569, 0.4       , 0.6313726 ],
        [0.23921569, 0.40392157, 0.6431373 ],
        [0.23921569, 0.40392157

In [25]:
(X_train, y_train),(X_test, y_test) = cifar10.load_data()
print(X_train)

[[[[ 59  62  63]
   [ 43  46  45]
   [ 50  48  43]
   ...
   [158 132 108]
   [152 125 102]
   [148 124 103]]

  [[ 16  20  20]
   [  0   0   0]
   [ 18   8   0]
   ...
   [123  88  55]
   [119  83  50]
   [122  87  57]]

  [[ 25  24  21]
   [ 16   7   0]
   [ 49  27   8]
   ...
   [118  84  50]
   [120  84  50]
   [109  73  42]]

  ...

  [[208 170  96]
   [201 153  34]
   [198 161  26]
   ...
   [160 133  70]
   [ 56  31   7]
   [ 53  34  20]]

  [[180 139  96]
   [173 123  42]
   [186 144  30]
   ...
   [184 148  94]
   [ 97  62  34]
   [ 83  53  34]]

  [[177 144 116]
   [168 129  94]
   [179 142  87]
   ...
   [216 184 140]
   [151 118  84]
   [123  92  72]]]


 [[[154 177 187]
   [126 137 136]
   [105 104  95]
   ...
   [ 91  95  71]
   [ 87  90  71]
   [ 79  81  70]]

  [[140 160 169]
   [145 153 154]
   [125 125 118]
   ...
   [ 96  99  78]
   [ 77  80  62]
   [ 71  73  61]]

  [[140 155 164]
   [139 146 149]
   [115 115 112]
   ...
   [ 79  82  64]
   [ 68  70  55]
   [ 67  69

In [29]:
print(y_test)
print(type(y_train))

[[3]
 [8]
 [8]
 ...
 [5]
 [1]
 [7]]
(50000, 1)


In [6]:
# floatに型変換
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
print(X_train)
# 各画素値を正規化
X_train /= 255.0
X_test /= 255.0


[[[[ 59.  62.  63.]
   [ 43.  46.  45.]
   [ 50.  48.  43.]
   ...
   [158. 132. 108.]
   [152. 125. 102.]
   [148. 124. 103.]]

  [[ 16.  20.  20.]
   [  0.   0.   0.]
   [ 18.   8.   0.]
   ...
   [123.  88.  55.]
   [119.  83.  50.]
   [122.  87.  57.]]

  [[ 25.  24.  21.]
   [ 16.   7.   0.]
   [ 49.  27.   8.]
   ...
   [118.  84.  50.]
   [120.  84.  50.]
   [109.  73.  42.]]

  ...

  [[208. 170.  96.]
   [201. 153.  34.]
   [198. 161.  26.]
   ...
   [160. 133.  70.]
   [ 56.  31.   7.]
   [ 53.  34.  20.]]

  [[180. 139.  96.]
   [173. 123.  42.]
   [186. 144.  30.]
   ...
   [184. 148.  94.]
   [ 97.  62.  34.]
   [ 83.  53.  34.]]

  [[177. 144. 116.]
   [168. 129.  94.]
   [179. 142.  87.]
   ...
   [216. 184. 140.]
   [151. 118.  84.]
   [123.  92.  72.]]]


 [[[154. 177. 187.]
   [126. 137. 136.]
   [105. 104.  95.]
   ...
   [ 91.  95.  71.]
   [ 87.  90.  71.]
   [ 79.  81.  70.]]

  [[140. 160. 169.]
   [145. 153. 154.]
   [125. 125. 118.]
   ...
   [ 96.  99.  78.]
 

In [7]:
#print(X_train)
print(type(X_train))
print(X_train.shape)
print(X_train.size)
print(50000*32*32*3)
print(len(X_train))

<class 'numpy.ndarray'>
(50000, 32, 32, 3)
153600000
153600000
50000


In [8]:
print([len(v) for v in X_train])
#32x32の画素数でさらにリストの中にRGBの3要素がある

[32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,

In [9]:
nb_classes = 10

Y_train = to_categorical(y_train, nb_classes)
Y_test = to_categorical(y_test, nb_classes)
print(y_train)
print(Y_train)

[[6]
 [9]
 [9]
 ...
 [9]
 [1]
 [1]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [15]:
# モデルの定義
model = Sequential()

model.add(Conv2D(32,3,input_shape=(32,32,3)))
model.add(Activation('relu'))
model.add(Conv2D(32,3))
model.add(Activation('relu'))
model.add(MaxPool2D(pool_size=(2,2)))

model.add(Conv2D(64,3))
model.add(Activation('relu'))
model.add(MaxPool2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(1024))
model.add(Activation('relu'))
model.add(Dropout(0.5))#1.0

model.add(Dense(nb_classes, activation='softmax'))

adam = Adam(lr=1e-4)

model.compile(optimizer=adam, loss='categorical_crossentropy', metrics=["accuracy"])

In [21]:
#エポック数　100
nb_epoch = 10

#バッチサイズ　500
batch_size = 500

history = model.fit(X_train, Y_train, batch_size=batch_size, epochs=nb_epoch, verbose=1, validation_split=0.1)

Epoch 1/10
90/90 [==============================] - 46s 510ms/step - loss: 1.2441 - accuracy: 0.5620 - val_loss: 1.2137 - val_accuracy: 0.5778
Epoch 2/10
90/90 [==============================] - 56s 619ms/step - loss: 1.2084 - accuracy: 0.5753 - val_loss: 1.2014 - val_accuracy: 0.5794
Epoch 3/10
90/90 [==============================] - 51s 569ms/step - loss: 1.1803 - accuracy: 0.5843 - val_loss: 1.1922 - val_accuracy: 0.5844
Epoch 4/10
90/90 [==============================] - 55s 609ms/step - loss: 1.1563 - accuracy: 0.5940 - val_loss: 1.1461 - val_accuracy: 0.5976
Epoch 5/10
90/90 [==============================] - 52s 574ms/step - loss: 1.1300 - accuracy: 0.6053 - val_loss: 1.1180 - val_accuracy: 0.6094
Epoch 6/10
90/90 [==============================] - 59s 651ms/step - loss: 1.1121 - accuracy: 0.6096 - val_loss: 1.1164 - val_accuracy: 0.6090
Epoch 7/10
90/90 [==============================] - 57s 633ms/step - loss: 1.0850 - accuracy: 0.6218 - val_loss: 1.0911 - val_accuracy: 0.6218

In [35]:
# モデルをプロット
from tensorflow.python.keras.utils.vis_utils import plot_model
plot_model(model, to_file='./model2.png')

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')
